'use client';

import { useState } from 'react';

interface CopySocialButtonProps {
  htmlContent: string;
}

/**
 * Converts Tailwind HTML generated by Gemini into clean Discord/Sleeper Markdown
 */
function convertHtmlToDiscordMarkdown(html: string): string {
  if (typeof window === 'undefined') return '';

  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const lines: string[] = [];

  // 1. Hero Header
  const heroHeader = doc.querySelector('h2');
  const heroText = doc.querySelector('div.mb-6 p');
  if (heroHeader) {
    lines.push(`**${heroHeader.textContent?.trim()}**`);
  }
  if (heroText) {
    lines.push(`_${heroText.textContent?.trim()}_\n`);
  }

  // 2. Weekly Honors & Badges Grid
  const honorsTitle = doc.querySelector('div.mb-8 h3');
  if (honorsTitle) {
    lines.push(`━━━━━━━━━━━━━━━━━━━━━━━`);
    lines.push(`**${honorsTitle.textContent?.trim()}**`);
  }

  const badgeCards = doc.querySelectorAll('div.mb-8 div.grid > div');
  badgeCards.forEach((card) => {
    const badgeLabel = card.querySelector('div')?.textContent?.replace(/\s+/g, ' ').trim();
    const teamName = card.querySelector('h4')?.textContent?.trim();
    const description = card.querySelector('p')?.textContent?.trim();

    if (badgeLabel && teamName) {
      lines.push(`\n${badgeLabel}: **${teamName}**`);
      if (description) lines.push(`> ${description}`);
    }
  });

  // 3. Matchups Breakdown
  const matchupsTitle = doc.querySelectorAll('h3')[1];
  if (matchupsTitle) {
    lines.push(`\n━━━━━━━━━━━━━━━━━━━━━━━`);
    lines.push(`**${matchupsTitle.textContent?.trim()}**\n`);
  }

  const matchupCards = doc.querySelectorAll('div.space-y-4 > div');
  matchupCards.forEach((card) => {
    const headerRow = card.querySelector('div.flex-wrap')?.textContent?.replace(/\s+/g, ' ').trim();
    const quote = card.querySelector('p.italic')?.textContent?.trim();
    const analysis = card.querySelectorAll('p')[1]?.textContent?.trim();

    if (headerRow) {
      lines.push(`• **${headerRow}**`);
    }
    if (quote) {
      lines.push(`  _${quote}_`);
    }
    if (analysis) {
      lines.push(`  > ${analysis}\n`);
    }
  });

  return lines.join('\n').trim();
}

export default function CopySocialButton({ htmlContent }: CopySocialButtonProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    if (!htmlContent) return;

    const markdownText = convertHtmlToDiscordMarkdown(htmlContent);

    try {
      await navigator.clipboard.writeText(markdownText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
  };

  return (
    <button
      onClick={handleCopy}
      disabled={!htmlContent}
      className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold font-mono bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white transition-all shadow-md shadow-indigo-950/50 active:scale-95"
    >
      {copied ? (
        <>
          <span className="text-emerald-300">✓</span>
          <span>Copied for Discord/Sleeper!</span>
        </>
      ) : (
        <>
          <span>💬</span>
          <span>Copy for Discord / Sleeper</span>
        </>
      )}
    </button>
  );
}